# Generated by Django 4.0.4 on 2022-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'db_Suscripcion',
            },
        ),
    ]
