# Generated by Django 4.0.4 on 2022-06-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_suscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='estado',
            new_name='estado_sus',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='usuario',
            new_name='usuario_sus',
        ),
    ]
