# Generated by Django 4.0.4 on 2022-05-12 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ingreso',
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'db_table': 'db_Carrito',
            },
        ),
    ]
