# Generated by Django 4.0.4 on 2022-06-12 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_historial_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
    ]
